libsoundio: soundio.h File Reference
soundio.h File Reference
Data Structures
struct SoundIoChannelLayout
The size of this struct is OK to use.
struct SoundIoSampleRateRange
The size of this struct is OK to use.
struct SoundIoChannelArea
The size of this struct is OK to use.
struct SoundIo
The size of this struct is not part of the API or ABI.
struct SoundIoDevice
The size of this struct is not part of the API or ABI.
struct SoundIoOutStream
The size of this struct is not part of the API or ABI.
struct SoundIoInStream
The size of this struct is not part of the API or ABI.
Macros
#define SOUNDIO_EXTERN_C
#define SOUNDIO_EXPORT SOUNDIO_EXTERN_C __attribute__((visibility ("default")))
#define SoundIoFormatS16NE SoundIoFormatS16LE
#define SoundIoFormatU16NE SoundIoFormatU16LE
#define SoundIoFormatS24NE SoundIoFormatS24LE
#define SoundIoFormatU24NE SoundIoFormatU24LE
#define SoundIoFormatS32NE SoundIoFormatS32LE
#define SoundIoFormatU32NE SoundIoFormatU32LE
#define SoundIoFormatFloat32NE SoundIoFormatFloat32LE
#define SoundIoFormatFloat64NE SoundIoFormatFloat64LE
#define SoundIoFormatS16FE SoundIoFormatS16BE
#define SoundIoFormatU16FE SoundIoFormatU16BE
#define SoundIoFormatS24FE SoundIoFormatS24BE
#define SoundIoFormatU24FE SoundIoFormatU24BE
#define SoundIoFormatS32FE SoundIoFormatS32BE
#define SoundIoFormatU32FE SoundIoFormatU32BE
#define SoundIoFormatFloat32FE SoundIoFormatFloat32BE
#define SoundIoFormatFloat64FE SoundIoFormatFloat64BE
#define SOUNDIO_MAX_CHANNELS 24
Enumerations
enum SoundIoError {
SoundIoErrorNone,
SoundIoErrorNoMem,
SoundIoErrorInitAudioBackend,
SoundIoErrorSystemResources,
SoundIoErrorOpeningDevice,
SoundIoErrorNoSuchDevice,
SoundIoErrorInvalid,
SoundIoErrorBackendUnavailable,
SoundIoErrorStreaming,
SoundIoErrorIncompatibleDevice,
SoundIoErrorNoSuchClient,
SoundIoErrorIncompatibleBackend,
SoundIoErrorBackendDisconnected,
SoundIoErrorInterrupted,
SoundIoErrorUnderflow,
SoundIoErrorEncodingString
}
See also soundio_strerror.
enum SoundIoChannelId {
SoundIoChannelIdInvalid,
SoundIoChannelIdFrontLeft,
SoundIoChannelIdFrontRight,
SoundIoChannelIdFrontCenter,
SoundIoChannelIdLfe,
SoundIoChannelIdBackLeft,
SoundIoChannelIdBackRight,
SoundIoChannelIdFrontLeftCenter,
SoundIoChannelIdFrontRightCenter,
SoundIoChannelIdBackCenter,
SoundIoChannelIdSideLeft,
SoundIoChannelIdSideRight,
SoundIoChannelIdTopCenter,
SoundIoChannelIdTopFrontLeft,
SoundIoChannelIdTopFrontCenter,
SoundIoChannelIdTopFrontRight,
SoundIoChannelIdTopBackLeft,
SoundIoChannelIdTopBackCenter,
SoundIoChannelIdTopBackRight,
SoundIoChannelIdBackLeftCenter,
SoundIoChannelIdBackRightCenter,
SoundIoChannelIdFrontLeftWide,
SoundIoChannelIdFrontRightWide,
SoundIoChannelIdFrontLeftHigh,
SoundIoChannelIdFrontCenterHigh,
SoundIoChannelIdFrontRightHigh,
SoundIoChannelIdTopFrontLeftCenter,
SoundIoChannelIdTopFrontRightCenter,
SoundIoChannelIdTopSideLeft,
SoundIoChannelIdTopSideRight,
SoundIoChannelIdLeftLfe,
SoundIoChannelIdRightLfe,
SoundIoChannelIdLfe2,
SoundIoChannelIdBottomCenter,
SoundIoChannelIdBottomLeftCenter,
SoundIoChannelIdBottomRightCenter,
SoundIoChannelIdMsMid,
SoundIoChannelIdMsSide,
SoundIoChannelIdAmbisonicW,
SoundIoChannelIdAmbisonicX,
SoundIoChannelIdAmbisonicY,
SoundIoChannelIdAmbisonicZ,
SoundIoChannelIdXyX,
SoundIoChannelIdXyY,
SoundIoChannelIdHeadphonesLeft,
SoundIoChannelIdHeadphonesRight,
SoundIoChannelIdClickTrack,
SoundIoChannelIdForeignLanguage,
SoundIoChannelIdHearingImpaired,
SoundIoChannelIdNarration,
SoundIoChannelIdHaptic,
SoundIoChannelIdDialogCentricMix,
SoundIoChannelIdAux,
SoundIoChannelIdAux0,
SoundIoChannelIdAux1,
SoundIoChannelIdAux2,
SoundIoChannelIdAux3,
SoundIoChannelIdAux4,
SoundIoChannelIdAux5,
SoundIoChannelIdAux6,
SoundIoChannelIdAux7,
SoundIoChannelIdAux8,
SoundIoChannelIdAux9,
SoundIoChannelIdAux10,
SoundIoChannelIdAux11,
SoundIoChannelIdAux12,
SoundIoChannelIdAux13,
SoundIoChannelIdAux14,
SoundIoChannelIdAux15
}
Specifies where a channel is physically located.
enum SoundIoChannelLayoutId {
SoundIoChannelLayoutIdMono,
SoundIoChannelLayoutIdStereo,
SoundIoChannelLayoutId2Point1,
SoundIoChannelLayoutId3Point0,
SoundIoChannelLayoutId3Point0Back,
SoundIoChannelLayoutId3Point1,
SoundIoChannelLayoutId4Point0,
SoundIoChannelLayoutIdQuad,
SoundIoChannelLayoutIdQuadSide,
SoundIoChannelLayoutId4Point1,
SoundIoChannelLayoutId5Point0Back,
SoundIoChannelLayoutId5Point0Side,
SoundIoChannelLayoutId5Point1,
SoundIoChannelLayoutId5Point1Back,
SoundIoChannelLayoutId6Point0Side,
SoundIoChannelLayoutId6Point0Front,
SoundIoChannelLayoutIdHexagonal,
SoundIoChannelLayoutId6Point1,
SoundIoChannelLayoutId6Point1Back,
SoundIoChannelLayoutId6Point1Front,
SoundIoChannelLayoutId7Point0,
SoundIoChannelLayoutId7Point0Front,
SoundIoChannelLayoutId7Point1,
SoundIoChannelLayoutId7Point1Wide,
SoundIoChannelLayoutId7Point1WideBack,
SoundIoChannelLayoutIdOctagonal
}
Built-in channel layouts for convenience.
enum SoundIoBackend {
SoundIoBackendNone,
SoundIoBackendJack,
SoundIoBackendPulseAudio,
SoundIoBackendAlsa,
SoundIoBackendCoreAudio,
SoundIoBackendWasapi,
SoundIoBackendDummy
}
enum SoundIoDeviceAim {
SoundIoDeviceAimInput,
SoundIoDeviceAimOutput
}
enum SoundIoFormat {
SoundIoFormatInvalid,
SoundIoFormatS8,
SoundIoFormatU8,
SoundIoFormatS16LE,
SoundIoFormatS16BE,
SoundIoFormatU16LE,
SoundIoFormatU16BE,
SoundIoFormatS24LE,
SoundIoFormatS24BE,
SoundIoFormatU24LE,
SoundIoFormatU24BE,
SoundIoFormatS32LE,
SoundIoFormatS32BE,
SoundIoFormatU32LE,
SoundIoFormatU32BE,
SoundIoFormatFloat32LE,
SoundIoFormatFloat32BE,
SoundIoFormatFloat64LE,
SoundIoFormatFloat64BE
}
Functions
SOUNDIO_EXPORT struct SoundIo * soundio_create (void)
Create a SoundIo context.
SOUNDIO_EXPORT void soundio_destroy (struct SoundIo *soundio)
SOUNDIO_EXPORT int soundio_connect (struct SoundIo *soundio)
This is a convenience function you could implement yourself if you wanted to.
SOUNDIO_EXPORT int soundio_connect_backend (struct SoundIo *soundio, enum SoundIoBackend backend)
Instead of calling soundio_connect you may call this function to try a specific backend.
SOUNDIO_EXPORT void soundio_disconnect (struct SoundIo *soundio)
SOUNDIO_EXPORT const char * soundio_strerror (int error)
Get a string representation of a SoundIoError.
SOUNDIO_EXPORT const char * soundio_backend_name (enum SoundIoBackend backend)
Get a string representation of a SoundIoBackend.
SOUNDIO_EXPORT int soundio_backend_count (struct SoundIo *soundio)
Returns the number of available backends.
SOUNDIO_EXPORT enum SoundIoBackend soundio_get_backend (struct SoundIo *soundio, int index)
get the available backend at the specified index (0 <= index < soundio_backend_count)
SOUNDIO_EXPORT bool soundio_have_backend (enum SoundIoBackend backend)
Returns whether libsoundio was compiled with backend.
SOUNDIO_EXPORT void soundio_flush_events (struct SoundIo *soundio)
When you call this, the SoundIo::on_devices_change and SoundIo::on_events_signal callbacks might be called.
SOUNDIO_EXPORT void soundio_wait_events (struct SoundIo *soundio)
This function calls soundio_flush_events then blocks until another event is ready or you call soundio_wakeup.
SOUNDIO_EXPORT void soundio_wakeup (struct SoundIo *soundio)
Makes soundio_wait_events stop blocking.
SOUNDIO_EXPORT bool soundio_channel_layout_equal (const struct SoundIoChannelLayout *a, const struct SoundIoChannelLayout *b)
Returns whether the channel count field and each channel id matches in the supplied channel layouts.
SOUNDIO_EXPORT const char * soundio_get_channel_name (enum SoundIoChannelId id)
SOUNDIO_EXPORT enum
SoundIoChannelId soundio_parse_channel_id (const char *str, int str_len)
Given UTF-8 encoded text which is the name of a channel such as "Front Left", "FL", or "front-left", return the corresponding SoundIoChannelId.
SOUNDIO_EXPORT int soundio_channel_layout_builtin_count (void)
Returns the number of builtin channel layouts.
SOUNDIO_EXPORT const struct
SoundIoChannelLayout * soundio_channel_layout_get_builtin (int index)
Returns a builtin channel layout. 0 <= index < soundio_channel_layout_builtin_count.
SOUNDIO_EXPORT const struct
SoundIoChannelLayout * soundio_channel_layout_get_default (int channel_count)
Get the default builtin channel layout for the given number of channels.
SOUNDIO_EXPORT int soundio_channel_layout_find_channel (const struct SoundIoChannelLayout *layout, enum SoundIoChannelId channel)
Return the index of channel in layout, or -1 if not found.
SOUNDIO_EXPORT bool soundio_channel_layout_detect_builtin (struct SoundIoChannelLayout *layout)
Populates the name field of layout if it matches a builtin one.
SOUNDIO_EXPORT const struct
SoundIoChannelLayout * soundio_best_matching_channel_layout (const struct SoundIoChannelLayout *preferred_layouts, int preferred_layout_count, const struct SoundIoChannelLayout *available_layouts, int available_layout_count)
Iterates over preferred_layouts.
SOUNDIO_EXPORT void soundio_sort_channel_layouts (struct SoundIoChannelLayout *layouts, int layout_count)
Sorts by channel count, descending.
SOUNDIO_EXPORT int soundio_get_bytes_per_sample (enum SoundIoFormat format)
Returns -1 on invalid format.
static int soundio_get_bytes_per_frame (enum SoundIoFormat format, int channel_count)
A frame is one sample per channel.
static int soundio_get_bytes_per_second (enum SoundIoFormat format, int channel_count, int sample_rate)
Sample rate is the number of frames per second.
SOUNDIO_EXPORT const char * soundio_format_string (enum SoundIoFormat format)
Returns string representation of format.
SOUNDIO_EXPORT int soundio_input_device_count (struct SoundIo *soundio)
When you call soundio_flush_events, a snapshot of all device state is saved and these functions merely access the snapshot data.
SOUNDIO_EXPORT int soundio_output_device_count (struct SoundIo *soundio)
Get the number of output devices.
SOUNDIO_EXPORT struct
SoundIoDevice * soundio_get_input_device (struct SoundIo *soundio, int index)
Always returns a device.
SOUNDIO_EXPORT struct
SoundIoDevice * soundio_get_output_device (struct SoundIo *soundio, int index)
Always returns a device.
SOUNDIO_EXPORT int soundio_default_input_device_index (struct SoundIo *soundio)
returns the index of the default input device returns -1 if there are no devices or if you never called soundio_flush_events.
SOUNDIO_EXPORT int soundio_default_output_device_index (struct SoundIo *soundio)
returns the index of the default output device returns -1 if there are no devices or if you never called soundio_flush_events.
SOUNDIO_EXPORT void soundio_device_ref (struct SoundIoDevice *device)
Add 1 to the reference count of device.
SOUNDIO_EXPORT void soundio_device_unref (struct SoundIoDevice *device)
Remove 1 to the reference count of device.
SOUNDIO_EXPORT bool soundio_device_equal (const struct SoundIoDevice *a, const struct SoundIoDevice *b)
Return true if and only if the devices have the same SoundIoDevice::id, SoundIoDevice::is_raw, and SoundIoDevice::aim are the same.
SOUNDIO_EXPORT void soundio_device_sort_channel_layouts (struct SoundIoDevice *device)
Sorts channel layouts by channel count, descending.
SOUNDIO_EXPORT bool soundio_device_supports_format (struct SoundIoDevice *device, enum SoundIoFormat format)
Convenience function.
SOUNDIO_EXPORT bool soundio_device_supports_layout (struct SoundIoDevice *device, const struct SoundIoChannelLayout *layout)
Convenience function.
SOUNDIO_EXPORT bool soundio_device_supports_sample_rate (struct SoundIoDevice *device, int sample_rate)
Convenience function.
SOUNDIO_EXPORT int soundio_device_nearest_sample_rate (struct SoundIoDevice *device, int sample_rate)
Convenience function.
SOUNDIO_EXPORT struct
SoundIoOutStream * soundio_outstream_create (struct SoundIoDevice *device)
Allocates memory and sets defaults.
SOUNDIO_EXPORT void soundio_outstream_destroy (struct SoundIoOutStream *outstream)
You may not call this function from the SoundIoOutStream::write_callback thread context.
SOUNDIO_EXPORT int soundio_outstream_open (struct SoundIoOutStream *outstream)
After you call this function, SoundIoOutStream:software_latency is set to the correct value.
SOUNDIO_EXPORT int soundio_outstream_start (struct SoundIoOutStream *outstream)
After you call this function, SoundIoOutStream::write_callback will be called.
SOUNDIO_EXPORT int soundio_outstream_begin_write (struct SoundIoOutStream *outstream, struct SoundIoChannelArea **areas, int *frame_count)
Call this function when you are ready to begin writing to the device buffer.
SOUNDIO_EXPORT int soundio_outstream_end_write (struct SoundIoOutStream *outstream)
Commits the write that you began with soundio_outstream_begin_write.
SOUNDIO_EXPORT int soundio_outstream_clear_buffer (struct SoundIoOutStream *outstream)
Clears the output stream buffer.
SOUNDIO_EXPORT int soundio_outstream_pause (struct SoundIoOutStream *outstream, bool pause)
If the underyling device supports pausing, this pauses the stream and prevents SoundIoOutStream::write_callback from being called.
SOUNDIO_EXPORT struct
SoundIoInStream * soundio_instream_create (struct SoundIoDevice *device)
Allocates memory and sets defaults.
SOUNDIO_EXPORT void soundio_instream_destroy (struct SoundIoInStream *instream)
You may not call this function from SoundIoInStream::read_callback.
SOUNDIO_EXPORT int soundio_instream_open (struct SoundIoInStream *instream)
After you call this function, SoundIoInStream::software_latency is set to the correct value.
SOUNDIO_EXPORT int soundio_instream_start (struct SoundIoInStream *instream)
After you call this function, SoundIoInStream::read_callback will be called.
SOUNDIO_EXPORT int soundio_instream_begin_read (struct SoundIoInStream *instream, struct SoundIoChannelArea **areas, int *frame_count)
Call this function when you are ready to begin reading from the device buffer.
SOUNDIO_EXPORT int soundio_instream_end_read (struct SoundIoInStream *instream)
This will drop all of the frames from when you called soundio_instream_begin_read.
SOUNDIO_EXPORT int soundio_instream_pause (struct SoundIoInStream *instream, bool pause)
If the underyling device supports pausing, this pauses the stream and prevents SoundIoInStream::read_callback from being called.
SOUNDIO_EXPORT struct
SoundIoRingBuffer * soundio_ring_buffer_create (struct SoundIo *soundio, int requested_capacity)
requested_capacity in bytes.
SOUNDIO_EXPORT void soundio_ring_buffer_destroy (struct SoundIoRingBuffer *ring_buffer)
SOUNDIO_EXPORT int soundio_ring_buffer_capacity (struct SoundIoRingBuffer *ring_buffer)
When you create a ring buffer, capacity might be more than the requested capacity for alignment purposes.
SOUNDIO_EXPORT char * soundio_ring_buffer_write_ptr (struct SoundIoRingBuffer *ring_buffer)
don't write more than capacity
SOUNDIO_EXPORT void soundio_ring_buffer_advance_write_ptr (struct SoundIoRingBuffer *ring_buffer, int count)
count in bytes.
SOUNDIO_EXPORT char * soundio_ring_buffer_read_ptr (struct SoundIoRingBuffer *ring_buffer)
don't read more than capacity
SOUNDIO_EXPORT void soundio_ring_buffer_advance_read_ptr (struct SoundIoRingBuffer *ring_buffer, int count)
count in bytes.
SOUNDIO_EXPORT int soundio_ring_buffer_fill_count (struct SoundIoRingBuffer *ring_buffer)
Returns how many bytes of the buffer is used, ready for reading.
SOUNDIO_EXPORT int soundio_ring_buffer_free_count (struct SoundIoRingBuffer *ring_buffer)
Returns how many bytes of the buffer is free, ready for writing.
SOUNDIO_EXPORT void soundio_ring_buffer_clear (struct SoundIoRingBuffer *ring_buffer)
Must be called by the writer.
Macro Definition Documentation
#define SOUNDIO_EXPORT SOUNDIO_EXTERN_C __attribute__((visibility ("default")))
#define SOUNDIO_EXTERN_C
#define SOUNDIO_MAX_CHANNELS 24
#define SoundIoFormatFloat32FE SoundIoFormatFloat32BE
Examples:
sio_microphone.c.
#define SoundIoFormatFloat32NE SoundIoFormatFloat32LE
Examples:
sio_microphone.c, and sio_sine.c.
#define SoundIoFormatFloat64FE SoundIoFormatFloat64BE
Examples:
sio_microphone.c.
#define SoundIoFormatFloat64NE SoundIoFormatFloat64LE
Examples:
sio_microphone.c, and sio_sine.c.
#define SoundIoFormatS16FE SoundIoFormatS16BE
Examples:
sio_microphone.c.
#define SoundIoFormatS16NE SoundIoFormatS16LE
Examples:
sio_microphone.c, and sio_sine.c.
#define SoundIoFormatS24FE SoundIoFormatS24BE
Examples:
sio_microphone.c.
#define SoundIoFormatS24NE SoundIoFormatS24LE
Examples:
sio_microphone.c.
#define SoundIoFormatS32FE SoundIoFormatS32BE
Examples:
sio_microphone.c.
#define SoundIoFormatS32NE SoundIoFormatS32LE
Examples:
sio_microphone.c, and sio_sine.c.
#define SoundIoFormatU16FE SoundIoFormatU16BE
Examples:
sio_microphone.c.
#define SoundIoFormatU16NE SoundIoFormatU16LE
Examples:
sio_microphone.c.
#define SoundIoFormatU24FE SoundIoFormatU24BE
Examples:
sio_microphone.c.
#define SoundIoFormatU24NE SoundIoFormatU24LE
Examples:
sio_microphone.c.
#define SoundIoFormatU32FE SoundIoFormatU32BE
Examples:
sio_microphone.c.
#define SoundIoFormatU32NE SoundIoFormatU32LE
Examples:
sio_microphone.c.
Enumeration Type Documentation
enum SoundIoBackend
Enumerator
SoundIoBackendNone
SoundIoBackendJack
SoundIoBackendPulseAudio
SoundIoBackendAlsa
SoundIoBackendCoreAudio
SoundIoBackendWasapi
SoundIoBackendDummy
enum SoundIoChannelId
Specifies where a channel is physically located.
Enumerator
SoundIoChannelIdInvalid
SoundIoChannelIdFrontLeft
SoundIoChannelIdFrontRight
SoundIoChannelIdFrontCenter
SoundIoChannelIdLfe
SoundIoChannelIdBackLeft
SoundIoChannelIdBackRight
SoundIoChannelIdFrontLeftCenter
SoundIoChannelIdFrontRightCenter
SoundIoChannelIdBackCenter
SoundIoChannelIdSideLeft
SoundIoChannelIdSideRight
SoundIoChannelIdTopCenter
SoundIoChannelIdTopFrontLeft
SoundIoChannelIdTopFrontCenter
SoundIoChannelIdTopFrontRight
SoundIoChannelIdTopBackLeft
SoundIoChannelIdTopBackCenter
SoundIoChannelIdTopBackRight
SoundIoChannelIdBackLeftCenter
SoundIoChannelIdBackRightCenter
SoundIoChannelIdFrontLeftWide
SoundIoChannelIdFrontRightWide
SoundIoChannelIdFrontLeftHigh
SoundIoChannelIdFrontCenterHigh
SoundIoChannelIdFrontRightHigh
SoundIoChannelIdTopFrontLeftCenter
SoundIoChannelIdTopFrontRightCenter
SoundIoChannelIdTopSideLeft
SoundIoChannelIdTopSideRight
SoundIoChannelIdLeftLfe
SoundIoChannelIdRightLfe
SoundIoChannelIdLfe2
SoundIoChannelIdBottomCenter
SoundIoChannelIdBottomLeftCenter
SoundIoChannelIdBottomRightCenter
SoundIoChannelIdMsMid
SoundIoChannelIdMsSide
SoundIoChannelIdAmbisonicW
SoundIoChannelIdAmbisonicX
SoundIoChannelIdAmbisonicY
SoundIoChannelIdAmbisonicZ
SoundIoChannelIdXyX
SoundIoChannelIdXyY
SoundIoChannelIdHeadphonesLeft
SoundIoChannelIdHeadphonesRight
SoundIoChannelIdClickTrack
SoundIoChannelIdForeignLanguage
SoundIoChannelIdHearingImpaired
SoundIoChannelIdNarration
SoundIoChannelIdHaptic
SoundIoChannelIdDialogCentricMix
SoundIoChannelIdAux
SoundIoChannelIdAux0
SoundIoChannelIdAux1
SoundIoChannelIdAux2
SoundIoChannelIdAux3
SoundIoChannelIdAux4
SoundIoChannelIdAux5
SoundIoChannelIdAux6
SoundIoChannelIdAux7
SoundIoChannelIdAux8
SoundIoChannelIdAux9
SoundIoChannelIdAux10
SoundIoChannelIdAux11
SoundIoChannelIdAux12
SoundIoChannelIdAux13
SoundIoChannelIdAux14
SoundIoChannelIdAux15
enum SoundIoChannelLayoutId
Built-in channel layouts for convenience.
Enumerator
SoundIoChannelLayoutIdMono
SoundIoChannelLayoutIdStereo
SoundIoChannelLayoutId2Point1
SoundIoChannelLayoutId3Point0
SoundIoChannelLayoutId3Point0Back
SoundIoChannelLayoutId3Point1
SoundIoChannelLayoutId4Point0
SoundIoChannelLayoutIdQuad
SoundIoChannelLayoutIdQuadSide
SoundIoChannelLayoutId4Point1
SoundIoChannelLayoutId5Point0Back
SoundIoChannelLayoutId5Point0Side
SoundIoChannelLayoutId5Point1
SoundIoChannelLayoutId5Point1Back
SoundIoChannelLayoutId6Point0Side
SoundIoChannelLayoutId6Point0Front
SoundIoChannelLayoutIdHexagonal
SoundIoChannelLayoutId6Point1
SoundIoChannelLayoutId6Point1Back
SoundIoChannelLayoutId6Point1Front
SoundIoChannelLayoutId7Point0
SoundIoChannelLayoutId7Point0Front
SoundIoChannelLayoutId7Point1
SoundIoChannelLayoutId7Point1Wide
SoundIoChannelLayoutId7Point1WideBack
SoundIoChannelLayoutIdOctagonal
enum SoundIoDeviceAim
Enumerator
SoundIoDeviceAimInput
capture / recording
SoundIoDeviceAimOutput
playback
enum SoundIoError
See also soundio_strerror.
Enumerator
SoundIoErrorNone
SoundIoErrorNoMem
SoundIoErrorInitAudioBackend
SoundIoErrorSystemResources
SoundIoErrorOpeningDevice
SoundIoErrorNoSuchDevice
SoundIoErrorInvalid
SoundIoErrorBackendUnavailable
SoundIoErrorStreaming
SoundIoErrorIncompatibleDevice
SoundIoErrorNoSuchClient
SoundIoErrorIncompatibleBackend
SoundIoErrorBackendDisconnected
SoundIoErrorInterrupted
SoundIoErrorUnderflow
SoundIoErrorEncodingString
enum SoundIoFormat
Enumerator
SoundIoFormatInvalid
SoundIoFormatS8
Signed 8 bit.
SoundIoFormatU8
Unsigned 8 bit.
SoundIoFormatS16LE
Signed 16 bit Little Endian.
SoundIoFormatS16BE
Signed 16 bit Big Endian.
SoundIoFormatU16LE
Unsigned 16 bit Little Endian.
SoundIoFormatU16BE
Unsigned 16 bit Little Endian.
SoundIoFormatS24LE
Signed 24 bit Little Endian using low three bytes in 32-bit word.
SoundIoFormatS24BE
Signed 24 bit Big Endian using low three bytes in 32-bit word.
SoundIoFormatU24LE
Unsigned 24 bit Little Endian using low three bytes in 32-bit word.
SoundIoFormatU24BE
Unsigned 24 bit Big Endian using low three bytes in 32-bit word.
SoundIoFormatS32LE
Signed 32 bit Little Endian.
SoundIoFormatS32BE
Signed 32 bit Big Endian.
SoundIoFormatU32LE
Unsigned 32 bit Little Endian.
SoundIoFormatU32BE
Unsigned 32 bit Big Endian.
SoundIoFormatFloat32LE
Float 32 bit Little Endian, Range -1.0 to 1.0.
SoundIoFormatFloat32BE
Float 32 bit Big Endian, Range -1.0 to 1.0.
SoundIoFormatFloat64LE
Float 64 bit Little Endian, Range -1.0 to 1.0.
SoundIoFormatFloat64BE
Float 64 bit Big Endian, Range -1.0 to 1.0.
Function Documentation
SOUNDIO_EXPORT int soundio_backend_count (struct SoundIo * soundio)
Returns the number of available backends.
SOUNDIO_EXPORT const char* soundio_backend_name (enum SoundIoBackend backend)
Get a string representation of a SoundIoBackend.
SOUNDIO_EXPORT const struct SoundIoChannelLayout* soundio_best_matching_channel_layout (const struct SoundIoChannelLayout * preferred_layouts, int preferred_layout_count, const struct SoundIoChannelLayout * available_layouts, int available_layout_count)
Iterates over preferred_layouts.
Returns the first channel layout in preferred_layouts which matches one of the channel layouts in available_layouts. Returns NULL if none matches.
Examples:
sio_microphone.c.
SOUNDIO_EXPORT int soundio_channel_layout_builtin_count (void)
Returns the number of builtin channel layouts.
SOUNDIO_EXPORT bool soundio_channel_layout_detect_builtin (struct SoundIoChannelLayout * layout)
Populates the name field of layout if it matches a builtin one.
returns whether it found a match
SOUNDIO_EXPORT bool soundio_channel_layout_equal (const struct SoundIoChannelLayout * a, const struct SoundIoChannelLayout * b)
Returns whether the channel count field and each channel id matches in the supplied channel layouts.
SOUNDIO_EXPORT int soundio_channel_layout_find_channel (const struct SoundIoChannelLayout * layout, enum SoundIoChannelId channel)
Return the index of channel in layout, or -1 if not found.
SOUNDIO_EXPORT const struct SoundIoChannelLayout* soundio_channel_layout_get_builtin (int index)
Returns a builtin channel layout. 0 <= index < soundio_channel_layout_builtin_count.
SOUNDIO_EXPORT const struct SoundIoChannelLayout* soundio_channel_layout_get_default (int channel_count)
Get the default builtin channel layout for the given number of channels.
SOUNDIO_EXPORT int soundio_connect (struct SoundIo * soundio)
This is a convenience function you could implement yourself if you wanted to.
It tries soundio_connect_backend on all available backends in order. See also soundio_disconnect
Examples:
sio_list_devices.c, sio_microphone.c, and sio_sine.c.
SOUNDIO_EXPORT int soundio_connect_backend (struct SoundIo * soundio, enum SoundIoBackend backend)
Instead of calling soundio_connect you may call this function to try a specific backend.
See also soundio_disconnect
Examples:
sio_list_devices.c, sio_microphone.c, and sio_sine.c.
SOUNDIO_EXPORT struct SoundIo* soundio_create (void)
Create a SoundIo context.
You may create multiple instances of this to connect to multiple backends. See also soundio_destroy
Examples:
sio_list_devices.c, sio_microphone.c, and sio_sine.c.
SOUNDIO_EXPORT int soundio_default_input_device_index (struct SoundIo * soundio)
returns the index of the default input device returns -1 if there are no devices or if you never called soundio_flush_events.
Examples:
sio_list_devices.c, and sio_microphone.c.
SOUNDIO_EXPORT int soundio_default_output_device_index (struct SoundIo * soundio)
returns the index of the default output device returns -1 if there are no devices or if you never called soundio_flush_events.
Examples:
sio_list_devices.c, sio_microphone.c, and sio_sine.c.
SOUNDIO_EXPORT void soundio_destroy (struct SoundIo * soundio)
Examples:
sio_list_devices.c, sio_microphone.c, and sio_sine.c.
SOUNDIO_EXPORT bool soundio_device_equal (const struct SoundIoDevice * a, const struct SoundIoDevice * b)
Return true if and only if the devices have the same SoundIoDevice::id, SoundIoDevice::is_raw, and SoundIoDevice::aim are the same.
SOUNDIO_EXPORT int soundio_device_nearest_sample_rate (struct SoundIoDevice * device, int sample_rate)
Convenience function.
Returns the available sample rate nearest to sample_rate, rounding up.
SOUNDIO_EXPORT void soundio_device_ref (struct SoundIoDevice * device)
Add 1 to the reference count of device.
SOUNDIO_EXPORT void soundio_device_sort_channel_layouts (struct SoundIoDevice * device)
Sorts channel layouts by channel count, descending.
Examples:
sio_microphone.c.
SOUNDIO_EXPORT bool soundio_device_supports_format (struct SoundIoDevice * device, enum SoundIoFormat format)
Convenience function.
Returns whether format is included in the device's supported formats.
Examples:
sio_microphone.c, and sio_sine.c.
SOUNDIO_EXPORT bool soundio_device_supports_layout (struct SoundIoDevice * device, const struct SoundIoChannelLayout * layout)
Convenience function.
Returns whether layout is included in the device's supported channel layouts.
SOUNDIO_EXPORT bool soundio_device_supports_sample_rate (struct SoundIoDevice * device, int sample_rate)
Convenience function.
Returns whether sample_rate is included in the device's supported sample rates.
Examples:
sio_microphone.c.
SOUNDIO_EXPORT void soundio_device_unref (struct SoundIoDevice * device)
Remove 1 to the reference count of device.
Clean up if it was the last reference.
Examples:
sio_list_devices.c, sio_microphone.c, and sio_sine.c.
SOUNDIO_EXPORT void soundio_disconnect (struct SoundIo * soundio)
SOUNDIO_EXPORT void soundio_flush_events (struct SoundIo * soundio)
When you call this, the SoundIo::on_devices_change and SoundIo::on_events_signal callbacks might be called.
This is the only time those callbacks will be called. This must be called from the same thread as the thread in which you call these functions:
soundio_input_device_count
soundio_output_device_count
soundio_get_input_device
soundio_get_output_device
soundio_default_input_device_index
soundio_default_output_device_index
Examples:
sio_list_devices.c, sio_microphone.c, and sio_sine.c.
SOUNDIO_EXPORT const char* soundio_format_string (enum SoundIoFormat format)
Returns string representation of format.
Examples:
sio_list_devices.c.
SOUNDIO_EXPORT enum SoundIoBackend soundio_get_backend (struct SoundIo * soundio, int index)
get the available backend at the specified index (0 <= index < soundio_backend_count)
static int soundio_get_bytes_per_frame (enum SoundIoFormat format, int channel_count) inline static
A frame is one sample per channel.
References SoundIoChannelLayout::channel_count, and soundio_get_bytes_per_sample().
Referenced by soundio_get_bytes_per_second().
SOUNDIO_EXPORT int soundio_get_bytes_per_sample (enum SoundIoFormat format)
Returns -1 on invalid format.
Referenced by soundio_get_bytes_per_frame().
static int soundio_get_bytes_per_second (enum SoundIoFormat format, int channel_count, int sample_rate) inline static
Sample rate is the number of frames per second.
References soundio_get_bytes_per_frame().
SOUNDIO_EXPORT const char* soundio_get_channel_name (enum SoundIoChannelId id)
Examples:
sio_list_devices.c.
SOUNDIO_EXPORT struct SoundIoDevice* soundio_get_input_device (struct SoundIo * soundio, int index)
Always returns a device.
Call soundio_device_unref when done. index must be 0 <= index < soundio_input_device_count Returns NULL if you never called soundio_flush_events or if you provide invalid parameter values.
Examples:
sio_list_devices.c, and sio_microphone.c.
SOUNDIO_EXPORT struct SoundIoDevice* soundio_get_output_device (struct SoundIo * soundio, int index)
Always returns a device.
Call soundio_device_unref when done. index must be 0 <= index < soundio_output_device_count Returns NULL if you never called soundio_flush_events or if you provide invalid parameter values.
Examples:
sio_list_devices.c, sio_microphone.c, and sio_sine.c.
SOUNDIO_EXPORT bool soundio_have_backend (enum SoundIoBackend backend)
Returns whether libsoundio was compiled with backend.
SOUNDIO_EXPORT int soundio_input_device_count (struct SoundIo * soundio)
When you call soundio_flush_events, a snapshot of all device state is saved and these functions merely access the snapshot data.
When you want to check for new devices, call soundio_flush_events. Or you can call soundio_wait_events to block until devices change. If an error occurs scanning devices in a background thread, SoundIo::on_backend_disconnect is called with the error code. Get the number of input devices. Returns -1 if you never called soundio_flush_events.
Examples:
sio_list_devices.c, and sio_microphone.c.
SOUNDIO_EXPORT int soundio_instream_begin_read (struct SoundIoInStream * instream, struct SoundIoChannelArea ** areas, int * frame_count)
Call this function when you are ready to begin reading from the device buffer.
instream - (in) The input stream you want to read from.
areas - (out) The memory addresses you can read data from. It is OK to modify the pointers if that helps you iterate. There might be a "hole" in the buffer. To indicate this, areas will be NULL and frame_count tells how big the hole is in frames.
frame_count - (in/out) - Provide the number of frames you want to read; returns the number of frames you can actually read. The returned value will always be less than or equal to the provided value. If the provided value is less than frame_count_min from SoundIoInStream::read_callback this function returns with SoundIoErrorInvalid. It is your responsibility to call this function no more and no fewer than the correct number of times according to the frame_count_min and frame_count_max criteria from SoundIoInStream::read_callback. You must call this function only from the SoundIoInStream::read_callback thread context. After calling this function, read data from areas and then use soundio_instream_end_read` to actually remove the data from the buffer and move the read index forward. soundio_instream_end_read should not be called if the buffer is empty (frame_count == 0), but it should be called if there is a hole.
Examples:
sio_microphone.c.
SOUNDIO_EXPORT struct SoundIoInStream* soundio_instream_create (struct SoundIoDevice * device)
Allocates memory and sets defaults.
Next you should fill out the struct fields and then call soundio_instream_open.
Examples:
sio_microphone.c.
SOUNDIO_EXPORT void soundio_instream_destroy (struct SoundIoInStream * instream)
You may not call this function from SoundIoInStream::read_callback.
Examples:
sio_microphone.c.
SOUNDIO_EXPORT int soundio_instream_end_read (struct SoundIoInStream * instream)
This will drop all of the frames from when you called soundio_instream_begin_read.
You must call this function only from the SoundIoInStream::read_callback thread context. You must call this function only after a successful call to soundio_instream_begin_read.
Examples:
sio_microphone.c.
SOUNDIO_EXPORT int soundio_instream_open (struct SoundIoInStream * instream)
After you call this function, SoundIoInStream::software_latency is set to the correct value.
The next thing to do is call soundio_instream_start. If this function returns an error, the instream is in an invalid state and you must call soundio_instream_destroy on it.
Examples:
sio_microphone.c.
SOUNDIO_EXPORT int soundio_instream_pause (struct SoundIoInStream * instream, bool pause)
If the underyling device supports pausing, this pauses the stream and prevents SoundIoInStream::read_callback from being called.
Otherwise this returns SoundIoErrorIncompatibleDevice. You must call this function only from the SoundIoInStream::read_callback thread context. Pausing when already paused or unpausing when already unpaused has no effect and always returns SoundIoErrorNone.
SOUNDIO_EXPORT int soundio_instream_start (struct SoundIoInStream * instream)
After you call this function, SoundIoInStream::read_callback will be called.
Examples:
sio_microphone.c.
SOUNDIO_EXPORT int soundio_output_device_count (struct SoundIo * soundio)
Get the number of output devices.
Returns -1 if you never called soundio_flush_events.
Examples:
sio_list_devices.c, sio_microphone.c, and sio_sine.c.
SOUNDIO_EXPORT int soundio_outstream_begin_write (struct SoundIoOutStream * outstream, struct SoundIoChannelArea ** areas, int * frame_count)
Call this function when you are ready to begin writing to the device buffer.
outstream - (in) The output stream you want to write to.
areas - (out) The memory addresses you can write data to. It is OK to modify the pointers if that helps you iterate.
frame_count - (in/out) Provide the number of frames you want to write. Returned will be the number of frames you can actually write, which is also the number of frames that will be written when you call soundio_outstream_end_write. The value returned will always be less than or equal to the value provided. It is your responsibility to call this function exactly as many times as necessary to meet the frame_count_min and frame_count_max criteria from SoundIoOutStream::write_callback. You must call this function only from the SoundIoOutStream::write_callback thread context. After calling this function, write data to areas and then call soundio_outstream_end_write. If you call this function with frame_count less than the frame_count_min parameter from SoundIoOutStream::write_callback it returns SoundIoErrorInvalid. If this function returns an error, do not call soundio_outstream_end_write.
Examples:
sio_microphone.c, and sio_sine.c.
SOUNDIO_EXPORT int soundio_outstream_clear_buffer (struct SoundIoOutStream * outstream)
Clears the output stream buffer.
You must call this function only from the SoundIoOutStream::write_callback thread context.
SOUNDIO_EXPORT struct SoundIoOutStream* soundio_outstream_create (struct SoundIoDevice * device)
Allocates memory and sets defaults.
Next you should fill out the struct fields and then call soundio_outstream_open.
Examples:
sio_microphone.c, and sio_sine.c.
SOUNDIO_EXPORT void soundio_outstream_destroy (struct SoundIoOutStream * outstream)
You may not call this function from the SoundIoOutStream::write_callback thread context.
Examples:
sio_microphone.c, and sio_sine.c.
SOUNDIO_EXPORT int soundio_outstream_end_write (struct SoundIoOutStream * outstream)
Commits the write that you began with soundio_outstream_begin_write.
You must call this function only from the SoundIoOutStream::write_callback thread context. This function might return SoundIoErrorUnderflow but don't count on it.
Examples:
sio_microphone.c, and sio_sine.c.
SOUNDIO_EXPORT int soundio_outstream_open (struct SoundIoOutStream * outstream)
After you call this function, SoundIoOutStream:software_latency is set to the correct value.
The next thing to do is call soundio_instream_start. If this function returns an error, the outstream is in an invalid state and you must call soundio_outstream_destroy on it.
Examples:
sio_microphone.c, and sio_sine.c.
SOUNDIO_EXPORT int soundio_outstream_pause (struct SoundIoOutStream * outstream, bool pause)
If the underyling device supports pausing, this pauses the stream and prevents SoundIoOutStream::write_callback from being called.
Otherwise this returns SoundIoErrorIncompatibleDevice. You must call this function only from the SoundIoOutStream::write_callback thread context. Pausing when already paused or unpausing when already unpaused has no effect and always returns SoundIoErrorNone.
SOUNDIO_EXPORT int soundio_outstream_start (struct SoundIoOutStream * outstream)
After you call this function, SoundIoOutStream::write_callback will be called.
Examples:
sio_microphone.c, and sio_sine.c.
SOUNDIO_EXPORT enum SoundIoChannelId soundio_parse_channel_id (const char * str, int str_len)
Given UTF-8 encoded text which is the name of a channel such as "Front Left", "FL", or "front-left", return the corresponding SoundIoChannelId.
Returns SoundIoChannelIdInvalid for no match.
SOUNDIO_EXPORT void soundio_ring_buffer_advance_read_ptr (struct SoundIoRingBuffer * ring_buffer, int count)
count in bytes.
Examples:
sio_microphone.c.
SOUNDIO_EXPORT void soundio_ring_buffer_advance_write_ptr (struct SoundIoRingBuffer * ring_buffer, int count)
count in bytes.
Examples:
sio_microphone.c.
SOUNDIO_EXPORT int soundio_ring_buffer_capacity (struct SoundIoRingBuffer * ring_buffer)
When you create a ring buffer, capacity might be more than the requested capacity for alignment purposes.
This function returns the actual capacity.
SOUNDIO_EXPORT void soundio_ring_buffer_clear (struct SoundIoRingBuffer * ring_buffer)
Must be called by the writer.
SOUNDIO_EXPORT struct SoundIoRingBuffer* soundio_ring_buffer_create (struct SoundIo * soundio, int requested_capacity)
requested_capacity in bytes.
See also soundio_ring_buffer_destroy
Examples:
sio_microphone.c.
SOUNDIO_EXPORT void soundio_ring_buffer_destroy (struct SoundIoRingBuffer * ring_buffer)
SOUNDIO_EXPORT int soundio_ring_buffer_fill_count (struct SoundIoRingBuffer * ring_buffer)
Returns how many bytes of the buffer is used, ready for reading.
Examples:
sio_microphone.c.
SOUNDIO_EXPORT int soundio_ring_buffer_free_count (struct SoundIoRingBuffer * ring_buffer)
Returns how many bytes of the buffer is free, ready for writing.
Examples:
sio_microphone.c.
SOUNDIO_EXPORT char* soundio_ring_buffer_read_ptr (struct SoundIoRingBuffer * ring_buffer)
don't read more than capacity
Examples:
sio_microphone.c.
SOUNDIO_EXPORT char* soundio_ring_buffer_write_ptr (struct SoundIoRingBuffer * ring_buffer)
don't write more than capacity
Examples:
sio_microphone.c.
SOUNDIO_EXPORT void soundio_sort_channel_layouts (struct SoundIoChannelLayout * layouts, int layout_count)
Sorts by channel count, descending.
SOUNDIO_EXPORT const char* soundio_strerror (int error)
Get a string representation of a SoundIoError.
Examples:
sio_list_devices.c, sio_microphone.c, and sio_sine.c.
SOUNDIO_EXPORT void soundio_wait_events (struct SoundIo * soundio)
This function calls soundio_flush_events then blocks until another event is ready or you call soundio_wakeup.
Be ready for spurious wakeups.
Examples:
sio_list_devices.c, sio_microphone.c, and sio_sine.c.
SOUNDIO_EXPORT void soundio_wakeup (struct SoundIo * soundio)
Makes soundio_wait_events stop blocking.